### ISSUE TITLE
MVPリリースレビュー

### ISSUE THREAD

**Issue by tmtkzk0823** [Syamari/unexplored#38]
お疲れ様です！

こちらMVPリリースレビューになります！

### 技術
- `rubocop`のgemを使って、静的構文チェックもしてあげると良さそうです。
- アーティストを検索する時、「入力した名前に最も近いアーティストが取得される」かと思うのですが、思ってもいないアーティストが入力される可能性があるので、入力した値に対して候補を出し、その中から選べるようにしてあげると良さそうかと思いました。（APIでアーティストの一覧を先に取得するなど）
- AIに渡すプロンプトにユーザーからの情報をもう少し渡してあげても良さそうに思いました。（現状「genre」だけなので他の要素もプロンプトに渡せてあげられると良さそうです）

### ユーザビリティ
passwordの設定に「小文字の英語と数字」を必須にしているかと思うのですが、ユーザー登録失敗時、フラッシュメッセージにそのことが表示されずでしたので、「小文字、数字を含む8文字以上である必要があります」のフラッシュメッセージを表示してあげると、ユーザーにもエラーの内容が伝わるかと思いました。（コード上は文言が確認できたのですが、フラッシュメッセージには確認できずでした）

以上です！

全体的に良くできていて、ユーザビリティの高いアプリケーションだと思いました！

LGTMです！

上記の内容を本リリース実装するタスクに組み込み、スケジュールを立ててみてください。

スケジュール決まりましたら共有をお願いできればと思います。

また上記レビューに関して、質問などありましたらスレッドに記載いただいてご連絡ください！

**Comment by Syamari** [comment]
レビューありがとうございます！

ユーザビリティに関して、ユーザー登録時失敗時のメッセージを修正しました
また、技術に関してレビューで頂いた内容を入れた本リリースの、実装スケジュールをProjectに立てました！

**Comment by Syamari** [comment]
１点質問です！、よろしくお願いします

##  rubocopによる修正の設定（./rubocop.yml）に関しての質問

個人的に導入時のままの設定が厳しいと感じ現状は緩めてあるのですが、実際はポートフォリオの場合どの程度の設定にすべきなのかについて確信が持てておらず、何か参考にすべきものやアイデアが知りたいと考えています

**Comment by tmtkzk0823** [comment]
> 個人的に導入時のままの設定が厳しいと感じ現状は緩めてあるのですが、実際はポートフォリオの場合どの程度の設定にすべきなのかについて確信が持てておらず、何か参考にすべきものやアイデアが知りたいと考えています

一旦は
- インデントを整える
- 不要なスペースを削除
- (マジックナンバー)

上記3つの設定が守られていればいいかと思います！
マジックナンバーはrubocopでは指摘されないのですが、一般的には悪手になりますので、一緒に意識してもらえればと！

**Comment by Syamari** [comment]
承知しました
勉強になります、回答ありがとうございました！
